### ISSUE TITLE
Players can't pickup dropped bananas.

### ISSUE THREAD

**Issue by satoshiaaron** [kurt-stolle/exclserver#1]
Players can't pickup bananas that have been dropped. They just float around.

**Comment by khwstolle** [comment]
Any errors? I can pick them up fine on a listen server.

**Comment by satoshiaaron** [comment]
I seem to be able to have them picked up on Jail Break, but not on BHOP or DR

**Comment by satoshiaaron** [comment]
Seems to be sorted on DR now. Not to sure about Bunny Hop.

**Comment by satoshiaaron** [comment]
Fixed now, forgot to restart the server after mounting CSS content.

**Comment by khwstolle** [comment]
Ah yes! You've got to mount CS:S
