### ISSUE TITLE
Only commands Advert, editadvert, Snapshot

### ISSUE THREAD

**Issue by satoshiaaron** [kurt-stolle/exclserver#3]
Sometimes the only commands available are Advert, Editadvert and Snapshot

**Comment by khwstolle** [comment]
This seems to be related to your settings. Make some additions to the settings database table.

**Comment by satoshiaaron** [comment]
Are there meant to be Settings in the table already?

**Comment by satoshiaaron** [comment]
Deleted all of the plugins and re-added them. Fixed.
