### ISSUE TITLE
Prop positioning doesn't save

### ISSUE THREAD

**Issue by satoshiaaron** [kurt-stolle/exclserver#4]

**Comment by khwstolle** [comment]
Works fine for me. Any errors?

**Comment by satoshiaaron** [comment]
No errors. It happened on Casual Bananas some time back also.

**Comment by khwstolle** [comment]
This never happened on Casual Bananas and I can't replicate it on my side. Could you make a demo?

**Comment by satoshiaaron** [comment]
Seems I still can't record demos as I crash everytime
It seems it's only the Position that doesn't save. It will just return to the default position.
I think this is an easy fix, I'll try tomorrow.

**Comment by satoshiaaron** [comment]
Typo on LINE 46 of file /exclserver/core/cl_player_outfit.lua

pos = pos + (ang:Up() \* drawPos.y) + (ang:Forward() \* drawPos.y) + (ang:Right() \* drawPos.x)

SHOULD BE

pos = pos + (ang:Up() \* drawPos.z) + (ang:Forward() \* drawPos.y) + (ang:Right() \* drawPos.x)

**Comment by satoshiaaron** [comment]
I have also noticed that if players click save multiple times, the hat will save them amount of times. When it comes to deleting the prop you will need to delete the prop, rejoin server, delete again, and so on. Also, when you save a model and then override it by clicking another, it will have both saved, but the older one will be the one to show in that specific slot.

**Comment by khwstolle** [comment]
No idea how that got in there. Fixed
