### ISSUE TITLE
Blocking parts of DarkRP HUD

### ISSUE THREAD

**Issue by 60percentCaffeine** [kurt-stolle/exclserver#6]
ExclServer stops DarkRP's mayor elections from showing.

**Comment by James3045498** [comment]
Hello,

Alex I was just wondering if you have any issues loading the addon it self? Any errors in console? 
I just magically started to have some issues with it, whenever I tried to edit the MYSQL information.

[ERROR] addons/exclserver-master/lua/exclserver/core/sv_data.lua:15: bad argument #2 to 'initialize' (string expected, got nil)
  1. initialize - [C]:-1
   2. unknown - addons/exclserver-master/lua/exclserver/core/sv_data.lua:15
    3. include - [C]:-1
     4. Include - addons/exclserver-master/lua/autorun/z_init_exclserver.lua:98
      5. IncludeFolder - addons/exclserver-master/lua/autorun/z_init_exclserver.lua:123
       6. unknown - addons/exclserver-master/lua/autorun/z_init_exclserver.lua:128
 
 
Thanks.

**Comment by 60percentCaffeine** [comment]
@James3045498 I can't really tell you because I have modified my ExclServer copy, sorry. Also, I resolved my issue.

**Comment by James3045498** [comment]
Alex, can you chuck us a download man?

**Comment by 60percentCaffeine** [comment]
@James3045498 Sorry, I can't.
